services:
  dvwa:
    image: vulnerables/web-dvwa
    container_name: bruteforce_dvwa
    restart: unless-stopped
    ports:
      - "8080:80"

  redis:
    image: redis:7-alpine
    container_name: bruteforce_redis
    restart: unless-stopped
    volumes:
      - redis_data:/data

  labdb:
    image: mariadb:11
    container_name: bruteforce_labdb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=bruteforce
      - MYSQL_USER=labuser
      - MYSQL_PASSWORD=labpass
    volumes:
      - labdb_data:/var/lib/mysql

  monitor:
    build:
      context: .
    container_name: bruteforce_monitor
    restart: unless-stopped
    environment:
      - STORAGE_MODE=${STORAGE_MODE}

      - REDIS_HOST=redis
      - REDIS_DB=0

      - SQL_HOST=labdb
      - SQL_PORT=3306
      - SQL_DB=bruteforce
      - SQL_USER=labuser
      - SQL_PASSWORD=labpass

    depends_on:
      - redis
      - labdb
    ports:
      - "5000:5000"

  auth:
    build:
      context: .
    container_name: bruteforce_auth
    restart: unless-stopped
    command: ["python", "app_auth.py"]
    environment:
      - STORAGE_MODE=${STORAGE_MODE}
      - REDIS_HOST=redis
      - REDIS_DB=0

      - SQL_HOST=labdb
      - SQL_PORT=3306
      - SQL_DB=bruteforce
      - SQL_USER=labuser
      - SQL_PASSWORD=labpass

    depends_on:
      - redis
      - labdb
    ports:
      - "8081:8081"

volumes:
  redis_data:
  labdb_data:

